project_id = "etojigjmeselsqptjkil"

[functions.meta-assign-account]
verify_jwt = true

[functions.meta-sync]
verify_jwt = false

[functions.client-signup]
verify_jwt = false

[functions.record-access]
verify_jwt = false

[functions.process-email-queue]
verify_jwt = true

[functions.mercado-pago-webhook]
verify_jwt = false

[functions.create-marketplace-pix-order]
verify_jwt = false

[functions.check-marketplace-order-status]
verify_jwt = false

[functions.get-marketplace-download-link]
verify_jwt = false

[functions.referral-alerts]
verify_jwt = true
