
ALTER TABLE public.meta_ad_accounts
  ADD COLUMN IF NOT EXISTS timezone_name TEXT,
  ADD COLUMN IF NOT EXISTS account_created_time TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS disable_reason INTEGER,
  ADD COLUMN IF NOT EXISTS disable_reason_label TEXT,
  ADD COLUMN IF NOT EXISTS funding_source TEXT,
  ADD COLUMN IF NOT EXISTS balance NUMERIC DEFAULT 0,
  ADD COLUMN IF NOT EXISTS business_country_code TEXT,
  ADD COLUMN IF NOT EXISTS age NUMERIC,
  ADD COLUMN IF NOT EXISTS owner_business_name TEXT,
  ADD COLUMN IF NOT EXISTS score INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS score_label TEXT,
  ADD COLUMN IF NOT EXISTS spend_cap NUMERIC,
  ADD COLUMN IF NOT EXISTS pixel_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS page_count INTEGER DEFAULT 0;

ALTER TABLE public.meta_business_managers
  ADD COLUMN IF NOT EXISTS verification_status TEXT,
  ADD COLUMN IF NOT EXISTS primary_page TEXT,
  ADD COLUMN IF NOT EXISTS account_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS pixel_count INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS page_count INTEGER DEFAULT 0;
